"""add_booking_indexes

Revision ID: 806c8c1e0b7d
Revises: 2ab58863f678
Create Date: 2026-07-04 13:27:53.470179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806c8c1e0b7d'
down_revision: Union[str, Sequence[str], None] = '2ab58863f678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.create_index('idx_bookings_room_time', 'bookings', ['room_id', 'time_start', 'time_end'], unique=False)
    op.create_index('idx_bookings_user_id', 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bookings_user_id', table_name='bookings')
    op.drop_index('idx_bookings_room_time', table_name='bookings')
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###
